# OAuth 2.0-Client-ID "OxaTrade"
spring:
  security:
    oauth2: 
      client:
        registration:
          # OAuth 2.0-Google-Client
          # https://console.cloud.google.com/apis/credentials
          google:
            client-id: ${OAUTH2_GOOGLE_ID}
            client-secret: ${OAUTH2_GOOGLE_SECRET}
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
              - openid
          # OAuth 2.0-Facebook-Client
          # https://developers.facebook.com/apps/
          facebook:
            client-id: ${OAUTH2_FACEBOOK_ID}
            client-secret: ${OAUTH2_FACEBOOK_SECRET}
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - email

---
spring:
  config:
    activate:
      on-profile: dev
      
# custom:
oxa:
  cors:
    max-age-secs: 3600
    allowedOrigins: http://localhost:5173,http://localhost:8080
    