spring:
  config:
    activate:
      on-profile: dev
      
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/oxatrade?allowPublicKeyRetrieval=true&useSSL=false
    username: oxatrade
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    #show-sql: true
    
  flyway:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/oxatrade?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

---
spring:
  config:
    activate:
      on-profile: test
      
  #H2 Database Engine: File will be created automatic after run
  datasource:
    #url: jdbc:h2:file:~/BuyToSaleAdmin;AUTO_SERVER=TRUE;
    url: jdbc:h2:file:///./tmp/test-db
    name: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

  flyway:
    url: jdbc:h2:file:///./tmp/test-db;DB_CLOSE_DELAY=-1
    #locations: classpath:db/migration
    baseline-on-migrate: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: PUBLIC # H2 default schema for test databases